apiVersion: v1
kind: Secret
metadata:
  name: hospital-backend-secret
type: Opaque
data:
  DB_USERNAME: QWtwYW5wYQ==
  DB_PASSWORD: cGFzc3dvcmQxMjNBQkM=


## echo -n "root" | base64
## echo -n "password123ABC" | base64
